"""init

Revision ID: 74413b606a3f
Revises: cd5df77b04b7
Create Date: 2024-09-04 21:20:15.268355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74413b606a3f'
down_revision = 'cd5df77b04b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
